### ISSUE TITLE
Astro Theme Portal submission

### ISSUE THREAD

**Issue by sarah11918** [BlockLune/astro-dracula-blog#3]
Hi @BlockLune ! I'm reviewing the current submissions to the Astro Theme portal and I just wanted to let you know why we could not accept your theme at this time. 

Themes should be ready for other people to use, complete with instructions about how to install, get started, customize as well as draw attention to things people need to know about *your* template, not just a generic Astro project. Template listings should advertise what is special about your template, and READMEs should instruct people about the overall design and project structure, what they'll need to know etc.

You are welcome to resubmit later if you make these changes! Your site looks great and I'm sure people would want to try it out! We just have to set people up for success doing so. 🚀

**Comment by BlockLune** [comment]
@sarah11918 I understand what you're saying about the README and template details. I'll make the updates and ping you when it's all done. Appreciate the feedback!

**Comment by BlockLune** [comment]
I have updated my README, please check it for compliance. I will thank you if you can provide more suggestions!

**Comment by BlockLune** [comment]
The submission has been accepted.
